name: prisma
channels:
  - conda-forge
dependencies:
  - gdal=3.6.3
  - h5py=3.8.0
  - jinja2=3.1.2
  - mgrs=1.4.3
  - opencv=4.7.0
  - pandas=2.0.0
  - pyrsr=0.7.0
  - python=3.10
  - python-dateutil=2.8.2
  - scikit-image=0.19.3
  - sunpy=4.1.3
  - shapely=2.0.1
